import Head from 'next/head'
import { trpc } from '@/utils/trpc';
import { getOptionsForVote } from '@/utils/getRandomPokemon';
import { useState } from 'react';
import Image from 'next/image'
import Link from 'next/link';

const btn =
  "inline-flex items-center px-3 py-1.5 border border-gray-300 shadow-sm font-medium rounded-full text-gray-700 bg-white hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500";

export default function Home () {

  const [ids, updateIds] = useState(getOptionsForVote());

  const [first, second] = ids;

  const voteMutation = trpc.castVote.useMutation();

  // const firstPokemon = trpc.useQuery("get-pokemon-by-id", { id: first });
  const firstPokemon = trpc.getPokemon.useQuery({ id: first });
  const secondPokemon = trpc.getPokemon.useQuery({ id: second });

  const voteForRoundest = (vote: number) => {
    if (vote === first) {
      voteMutation.mutate({ votedFor: first, votedAgainst: second });
    } else {
      voteMutation.mutate({ votedFor: second, votedAgainst: first });
    }

    updateIds(getOptionsForVote());
  }

  const dataLoaded = 
    !firstPokemon.isLoading &&
    !secondPokemon.isLoading &&
    firstPokemon.data &&
    secondPokemon.data;

  return (
    <>
      <Head>
        <title>Roundest Mon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className='flex text-2xl justify-center items-end h-48' >Which Pokemon is Rounder?</div>
        <div className='w-screen flex flex-col justify-top items-center' >
          <div className='p-2' />
          {dataLoaded && <div className='border rounded p-8 flex justify-between items-center max-w-2xl' >
            <div className='w-64 flex flex-col items-center'>
              <Image width={256} height={256} alt="" src={firstPokemon.data?.spriteUrl!} className="w-full"/>
              <div className='text-xl text-center pb-4 capitalize mt-[-2rem]'>{firstPokemon.data?.name}</div>
              <button className={btn} onClick={() => voteForRoundest(first)}>Rounder</button>
            </div>
            <div className='p-8'>VS</div>
            <div className='w-64 flex flex-col items-center'>
              <Image width={256} height={256} alt="" src={secondPokemon.data?.spriteUrl!} className="w-full"/>
              <div className='text-xl text-center pb-4 capitalize mt-[-2rem]'>{secondPokemon.data?.name}</div>
              <button className={btn} onClick={() => voteForRoundest(second)}>Rounder</button>
            </div>
          </div>}
          {!dataLoaded && 
          <div className='py-14'>
            <img src='/rings.svg' className='w-48' />
          </div>}

        </div>
        <div className='absolute bottom-0 w-full text-xl text-center pb-2'>
          <a target={'_blank'} href='https://github.com/killacan/roundest-mon'>Github</a>
          {' | '}
          <Link href={`/results`}>Results</Link>
        </div>
      </main>
    </>
  )
}
